config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  get 'welcome/index'

  resources :articles do
    resources :comments, controller: 'articles/comments'
    resources :photos
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  has_many :photos, as: :imageable
  belongs_to :user
	validates :title, presence: true,
					  length: {minimum: 5}
  validate :user_id_should_be_present
  
   def user_id_should_be_present
    if user_id.nil? || !(User.where("id = ?", user_id).exists?)
      errors.add(:user_id, "Should be present")
    end
  end          
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates :body, presence: true 
  validate :article_id_should_be_present, :user_id_should_be_present

  def article_id_should_be_present
    if article_id.nil? || !(Article.where("id = ?", article_id).exists?)
      errors.add(:article_id, "Should be present")
    end
  end

  def user_id_should_be_present
    if user_id.nil? || !(User.where("id = ?", user_id).exists?)
      errors.add(:user_id, "Should be present")
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image
  do_not_validate_attachment_file_type :image
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.confirmed_at = Time.now
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  #http_basic_authenticate_with name: "user", password: "password",only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id
    @a = Article.find(params[:article_id])
    if(@comment.save)
      @flag = 1;
    else
      @flag = 0;
    end
    #redirect_to article_path(@article)
    respond_to do |format|  
            format.js { render 'comments/create'}
        end 
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @a = Article.find(params[:article_id])
    if(@comment.destroy)
      @flag = 2;
    else
      @flag = 3;
    end
    #redirect_to article_path(@article)
    respond_to do |format|  
            format.js { render 'comments/create'}
        end 
      #redirect_to article_path(@article)
    end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#http_basic_authenticate_with name: "user", password:"password",except:[:index, :show]
  before_filter :authenticate_user!
  around_filter :log_articles , only: :index
  include Ability
	def index
		#binding.pry
		Rails.logger.info("Startedgetting articles")
		@articles = Article.all.includes(:user)
											 .paginate(page: params[:page], 
											 	         per_page: 4)

	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit

		@article = Article.find(params[:id])
	end

	def create
		@author = User.find(current_user.id)
		@article = @author.articles.create(article_params)
		if(@article.save)
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		#if @article.user_id == current_user.id
		if Person.can_do?(@article.user_id, current_user.id)
			if @article.update(article_params)
				redirect_to @article 
			else
				render 'edit'
			end
		else
			flash[:error]="You are not authorized for this operation!!!"
			redirect_to article_path
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if current_user.email == "admin@gmail.com"
			@article.destroy
		else
			@article.isactive = 1
			@article.save
		end
		#@article.destroy
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title,:text)
	end
	def log_articles
		Rails.logger.info("Startedgetting articles")
		yield
		Rails.logger.info("Ended")
	end
end
#working in feature branch

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
# 	#http_basic_authenticate_with name: "user", password: "password",only: :destroy
# 	def create
# 		@article = Article.find(params[:article_id])
# 		@comment = @article.comments.new(comment_params)
#     @comment.user_id = current_user.id
#     @comment.save
# 		# redirect_to article_path(@article)a
# 	end

# 	def destroy
# 		@article = Article.find(params[:article_id])
# 		@comment = @article.comments.find(params[:id])
#     	@comment.destroy
#     	redirect_to article_path(@article)
#   	end

# 	private
# 	def comment_params
# 		params.require(:comment).permit(:body)
# 	end
# end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @article = Article.find(params[:article_id])
  end
  def new
    @photo = Photo.new
  end
  def show
    @article = Article.find(params[:article_id])
  end
  def create
    @article = Article.find(params[:article_id])
    @photo = Photo.new(photo_params)
    @photo.imageable = @article
    @photo.save
    redirect_to article_path(@article)
  end

  def destroy
  @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to 'https://scotch.io/tutorials/integrating-social-login-in-a-ruby-on-rails-application'
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

  private 

  def photo_params
    params.require(:photo).permit(:title, :image)
  end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < ApplicationController
  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
      if is_navigational_format?
        flash[:notice] = "Successfunlly logged In"
      end 
    else
      flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
      redirect_to new_user_registration_url
    end 
  end

  def failure
  flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
  redirect_to new_user_registration_url
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class = "error">
      <h2>
        <%= pluralize(@article.errors.count, "error")%>
        prohibited this article from being saved
      </h2>
      
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>    
    </div>
  <% end %>

  <p>
    <%= f.label :title, class: "labels" %><br>
    <%= f.text_field :title ,class: "input_area"%>
  </p>
 
  <p>
    <%= f.label :name,'Content', class: "labels" %><br>
    <%= f.text_area :text ,class: "text_area" %>
  </p>
 
  <p>
    <%= f.submit class: 'submit_btn' %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<body class = "container-fluid"><center>
<h1>Editing article</h1>
 <%= render 'form' %>
<%= link_to 'Home', articles_path %>
</center></body>

app/views/articles/index.html.erb
  <br/><body class="tb wood container-fluid">
    <center>
    <h1>Listing articles</h1>
    <p class = "p1"><%= link_to 'New article', new_article_path %></p>
    <table class = "table table-bordered">
      <tr>
        <th>Title</th>
        <th>Author</th>
      
      </tr>
      <% if current_user.email != "admin@gmail.com" %>
        <% @articles.each do |article| %>
          <% if article.isactive.nil? %>
            <tr>
              <td><div class = "td1"><%=link_to article.title, article_path(article)%></div></td>
              <td><%= article.user.email %></td>
              <% if article.user_id == current_user.id %>
                <td><%= link_to'Edit', edit_article_path(article) %></td>
                <td><%= link_to'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure'} %></td>
              <% end %> 
            </tr>
          <% end %>
        <% end %>
      <% else %>
        <% @articles.each do |article| %>
          <tr>
            <td><div class = "td1"><%=link_to article.title, article_path(article)%></div></td>
            <td><%= article.user.email %></td>
            <td><%= link_to'Edit', edit_article_path(article) %></td>
            <td><%= link_to'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure'} %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <div class = "row">
      <div class = "col-sm-auto page1"><%= will_paginate @articles %></div>
    </div>
    </center>
  </body>

app/views/articles/new.html.erb
  <body class = "container-fluid"><center>
    <h2>Add New Article</h2>
   <%= render 'form' %>  
  <%= link_to 'Home', articles_path%>
</center>
</body>

app/views/articles/show.html.erb
	<body class = "container-fluid">
    <div class = "row" >
		<div class = "col-sm-auto">
			<center><div class = "link1"><%= link_to 'Home', articles_path%></div></center></div>
      <% if @article.user_id == current_user.id %><div class = "col-sm-auto">
			   <center><div class = "link1"><%= link_to'Edit', edit_article_path(@article) %></div></center></div>
         <div class = "col-sm-auto">
         <center><div class = "link1"><%= link_to'show Images', "/articles/#{@article.id}/photos" %></div></center></div>
			<% end %>
		</div>
    <br/>
		<div class = " row">
			<div class = "col-sm-12 font24"><p><center>
	  			<strong class = "font32">Title : </strong>
	  			<%= @article.title %>
			</center></p>
    </div>
   <div class = "brown">
			<p class = "brown"><center>
	  			<%= @article.text %>
			</center></p>
		</div>
  </div>

		
		<div id = "comment_box" class = "d2 green">
			<h1 class = "wood">Comments :</h1>
			<% @article.comments.each do |comment| %>
	  			<p>
	    			<strong class = "usr">User :</strong>
	    			<%= User.find(comment.user_id).email %>
	  			</p>
	 
				<p>
	    			<strong class = "usr">Comment :</strong>
	    			<%= comment.body %>
	  			</p>

				<p>
				<%= link_to 'Delete Comment', [comment.article, comment],
                 remote: true,
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	 			</p>
			<% end %>
		</div>
    <div id = "messg">
    </div>

		<div class = "d3"><center>
			<h2 class = "white">Add a comment :</h2>
			<%= form_for([@article, @article.comments.build],remote: true) do |f| %>
		  		<p>
		   			<%= f.label :Comment, class: 'text_area wood' %><br>
		    		<%= f.text_area :body, class: 'text_area wood comm_class' %>
		  		</p>
		  		<p>
		    		<%= f.submit class: 'submit_btn' %>
		  		</p>
			<% end %></center>
		</div>


<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for [@article, @article.photos.build], html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

</body>

app/views/articles/show_updated.js.erb
//$("<p><%= @comment.body %></p>").appendTo("#comment_box");
var comm = '<div>\
              <p>\
            <strong class = "usr">User :</strong>\
            <%= @comment.user.email %>\
          </p>\
        <p>\
            <strong class = "usr">Comment :</strong>\
            <%= @comment.body %>\
          </p>\
        <p>\
        <%= link_to "Delete Comment", [@comment.article, @comment],\
                 method: :delete,\
                 data: { confirm: "Are you sure?" } %>\
        </p>\
            </div>';

$(comm).appendTo("#comment_box");            

app/views/comments/create.js.erb
/*      <h1>Comments :</h1>\
      <% @article.comments.each do |comment| %>\
          <p>\  
            <strong class = "usr">User :</strong>\
            <%= comment.user.email %>\
          </p>\
        <p>\
            <strong class = "usr">Comment :</strong>\
            <%= comment.body %>\
          </p>\
        <p>\
        <%= link_to "Delete Comment", [comment.article, comment],\
                 method: :delete,\
                 data: { confirm: "Are you sure?" } %>\
        </p>\
      <% end %>\
    </div>';

var comm = '<div>\
              <p>\
            <strong class = "usr">User :</strong>\
            <%= @comment.user.email %>\
          </p>\
        <p>\
            <strong class = "usr">Comment :</strong>\
            <%= @comment.body %>\
          </p>\
        <p>\
        <%= link_to "Delete Comment", [@comment.article, @comment],\
                 method: :delete,\
                 data: { confirm: "Are you sure?" } %>\
        </p>\
            </div>';*/

var comm = '<div>\
            <h1 class = "usr">Comments :</h1>\
            <% @a.comments.each do |commen| %>\
            <p>\
            <strong class = "usr">User :</strong>\
            <%= commen.user.email %>\
            </p>\
        <p>\
            <strong class = "usr">Comment :</strong>\
            <%= commen.body %>\
          </p>\
        <p>\
        <%= link_to "Delete Comment", [commen.article, commen],\
                 remote: true,\
                 method: :delete,\
                 data: { confirm: "Are you sure?" } %>\
        </p>\
         <% end %>\
            </div>';

var message = '<center><div>\
               <% if @flag == 1 %>\
               <p> Your Comment has been added successfully </p>\
               <% elsif @flag == 0 %>\
               <p> creation failed </p>\
               <%elsif @flag == 2 %>\
               <p> comment deleted successfully </p>\
               <% elsif @flag == 3 %>\
               <p> Deletion failed </p>\
               <% end %>\
               </div></center>'

$('#comment_box').html(comm);  
$('.comm_class').val(" ");
$('#messg').html(message);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet", type='text/css'>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width = device-width, initial-scale = 1, shrink-to-fit = no">
</head>
<body>
  <div class="container-fluid"><center>
      <% flash.each do |key, value| %>
        <div class="<%= key %>"><%= value %></div>
      <% end %>
  </center>
<div class = "hidd">
  <center><div class="dropdown">
    <button class="btn btn-primary toggle colr fr" type="button" data-toggle="dropdown">
    <span class="caret"></span></button>
    <div class = "row fr">
      <% if !(current_user.nil?)%>
    <ul class="dropdown-menu">
      <li><div class = "col-sm-auto link2"><center><%= current_user.email %></center></div></li>
      <li><div class = "col-sm-auto link2"><center><%= link_to 'Log out', 'users/sign_out', method: :delete %></center></div></li>
      <li><div class = "col-sm-auto link2"><center><%= link_to "Change your password", edit_user_registration_path %></center></div></li>
    </ul>
    <%end%>
  </div>
  </div></center>
</div>
<div class = "row fr hid2">
      <% if !(current_user.nil?)%>
      <div class = "col-sm-auto link2 wood"><center><%= current_user.email %></center></div>
        <div class = "col-sm-auto link2"><center><%= link_to 'Log out', 'users/sign_out', method: :delete %></center></div>
        
        <div class = "col-sm-auto link2"><center><%= link_to "Change your password", edit_user_registration_path %></center></div>
      <% end %>
    </div> 
  </div>
<%= yield %>
</body>
</html>

app/views/photos/index.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>
<center><div class = "link1"><%= link_to 'Home', articles_path%></div></center>
<div>
  <% @article.photos.each do |photo| %>
    <div class="comp">
      <!-- Renders image -->
      <%= link_to image_tag(photo.image.url), photo.image.url, target: '_blank' %>
    </div>
    <div>
      <h4>Delete : <%=link_to photo.title,"/articles/:article_id/photos/#{photo.id}", method: :delete, data: {confirm: 'Are you sure'} %></h4>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<body>
  <center>
    <h1>Welcome to the Blog App</h1>
     <p class = "p1"><%= link_to 'Articles List', '/articles' %></p>
  </center>
</body>